import argparse

parser = argparse.ArgumentParser(description='VadCLIP')
parser.add_argument('--seed', default=234, type=int)

parser.add_argument('--embed-dim', default=512, type=int)
parser.add_argument('--snippets', default=256, type=int)
parser.add_argument('--visual-width', default=512, type=int)
parser.add_argument('--visual-head', default=1, type=int)
parser.add_argument('--visual-layers', default=2, type=int)
parser.add_argument('--attn-window', default=8, type=int)
parser.add_argument('--prompt-prefix', default=10, type=int)
parser.add_argument('--prompt-postfix', default=10, type=int)
parser.add_argument('--classes-num', default=14, type=int)

parser.add_argument('--max-epoch', default=20, type=int)
parser.add_argument('--model-path', default='/home/username/VadCLIP/saved_model/fused_data_before_classification/model_ucf.pth')
parser.add_argument('--use-checkpoint', default=False, type=bool)
parser.add_argument('--checkpoint-path', default='/home/username/VadCLIP/saved_model/UCF/')
parser.add_argument('--batch-size', default=64, type=int)
parser.add_argument('--train-list', default='/home/username/VadCLIP/list/ucf_CLIP_rgb_vit14.csv')
parser.add_argument('--test-list', default='/home/username/VadCLIP/list/ucf_CLIP_rgbtest_vit14.csv')
parser.add_argument('--gt-path', default='/home/username/VadCLIP/list/gt_ucf.npy')
parser.add_argument('--gt-segment-path', default='/home/username/VadCLIP/list/gt_segment_ucf.npy')
parser.add_argument('--gt-label-path', default='/home/username/VadCLIP/list/gt_label_ucf.npy')
parser.add_argument('--contrast', default=False, type=bool)
parser.add_argument('--fusion', default='cross_attn', type=str)

parser.add_argument('--lr', default=2e-4)
parser.add_argument('--scheduler-rate', default=0.1)
parser.add_argument('--scheduler-milestones', default=[5, 10])
parser.add_argument('--frame_selection', default='text_grounded', type=str)
parser.add_argument('--feat_encoder', default='vit14', type=str)